### PR TITLE
Fix scraping logic after site changes

### LINKED ISSUE #7: Returns 0001-01-01 for /api/v1/rr, and empty Collections for /api/v1/rrext
Hi there, thanks for building this! I've been running it for a while, but occasionally see errors where it returns `0001-01-01` for the dates, which break my home assistant integration.

I just built and pushed the latest commit and deployed the Docker container. This is what I'm currently seeing:

```
curl "http://10.5.7.10:32769/api/v1/rr/?addr=MYADDRESS"
{"rubbish":"0001-01-01","recycle":"0001-01-01","foodscraps":"0001-01-01","address":"MYADDRESS"}

curl "http://10.5.7.10:32769/api/v1/rrext/?addr=MYADDRESS"
{"Collections":[],"Address":{"ACRateAccountKey":"*******","Address":"MYADDRESS","Suggestion":"MYADDRESS"}}
```

I checked the URL in a web browser and it's working fine:

https://www.aucklandcouncil.govt.nz/rubbish-recycling/rubbish-recycling-collections/Pages/collection-day-detail.aspx?an=****

Thanks!

### PR DESCRIPTION
**Pull request by ndbroadbent**
It looks like the website has been updated, so I fixed the scraping logic.

Screenshot 2024-04-20 at 9 04 16 PM

Fixes #7 

I'm running this change locally and it's working for me now:

image

```
❯ curl "http://10.5.7.10:32769/api/v1/rrext/?addr=MYADDRESS"
{"Collections":[{"Day":"Friday 26 April","Date":"2024-04-26T00:00:00+12:00","Rubbish":true,"Recycle":false,"FoodScraps":false},{"Day":"Friday 26 April","Date":"2024-04-26T00:00:00+12:00","Rubbish":false,"Recycle":false,"FoodScraps":true},{"Day":"Thursday 2 May","Date":"2024-05-02T00:00:00+12:00","Rubbish":false,"Recycle":true,"FoodScraps":false}],"Address":{"ACRateAccountKey":"KEY","Address":"MYADDRESS","Suggestion":"MYADDRESS"}}

~
❯ curl "http://10.5.7.10:32769/api/v1/rr/?addr=MYADDRESS"
{"rubbish":"2024-04-26","recycle":"2024-05-02","foodscraps":"2024-04-26","address":"MYADDRESS"}
```

### CODE REVIEW

**Comment by rusq** [comment]
Hey @ndbroadbent, thank you!

**Comment by rusq** [comment]
Looks like the test are upset

**Comment by rusq** [comment]
Fixed the tests, but obviously can't push into your branch.  Created a new branch, will merge it there, and then update the tests

**Comment by ndbroadbent** [comment]
Oh right sorry about the tests! Thanks for the fix!

**Comment by rusq** [comment]
Np, thanks for the PR!

**Pull request merged**
